name: Update Token List

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-token-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install web3 requests

      - name: Run the update script and get version
        id: get_version
        run: |
          VERSION=$(python ./src/update.py)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if git commit -m "Token list update v${{ env.VERSION }}"; then
            git push
          else
            echo "No changes to commit"
